name: "deploy workflow"

on:
  push:
    branches:
      - main

jobs:
  # build, test, deploy
  build-and-push-image:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "."
          file: dockerfile
          push: true
          tags: temmie01/artline:${{github.sha}}

      - name: Deploy-container
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker stop model
            docker rm -f model
            docker pull temmie01/artline:${{github.sha}}
            docker run -d --name model -p 80:8080  temmie01/artline:${{github.sha}}
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PK }}